# --- Core settings ---------------------------------------------------------

# Optional, but usually nice to set explicitly
line-length = 88
target-version = "py310"

# --- Lint rule selection ---------------------------------------------------

include = [
    "pyproject.toml",
    "go2_robot_sdk/**"
]

exclude = [
    "go2_robot_sdk/meshes/**",
    "go2_robot_sdk/urdf/**",
    "go2_robot_sdk/external_lib/**",
    "go2_robot_sdk/dae/**",
    "go2_robot_sdk/calibration/**",
]

[lint]
select = [
    "ALL"
]

ignore = [
    # Annotations for __init__, __enter__, __exit__, *args, **kwargs are annoying and not needed
    "ANN204", "ANN401", "ANN002", "ANN003",
    "D", # pydocstring, lots of annoying things related to docstring formatting
    "W", # pycodestyle, lots of opinionated warnings, all of which should be dealt by the formatter
    "Q", # opinionated about single and double quotes. again, formatter should deal with this
    "FBT", # opinionated about booleans. consider enabling eventually
    "TD", "FIX", # warnings about todos, spammy and cumbersome
    "SIM", # suggests simplifications. kind of opinionated and not really important. Spammy too.
    
    # stuff formatter should fix, leave alone if formatter doesn't fix
    "I001", # import sorting. 
    "E501", # line-too-long
    "COM812", # missing-trailing-comma

    # too-many-X
    "PLR",

    "TRY003", # don't use exception messages, seems like a bad rule 
    "TRY300", # else-suggestion. way too opinionated
    
    "PIE790", # unnecessary-pass-statement, its nice visually to include a pass or ... sometimes
    
    # rules about f-strings. kind of annoying to maintain
    "F541", "G004", "EM101", "EM102", # f-string without args / f-strings in logging
    
    # return statement related. opinionated, sometimes its nice to name things or be explicit
    "RET",

    "TC006", # use quotes in typing.cast, purely stylistic
    "C",
    "N818", # no-Error-suffix on new exceptions. It's better we don't do this to avoid collisions with builtins
    
    "PT",
]

